module.exports = [
    {
        city: "Pemberton",
        latitude: 50.3413,
        longitude: -122.4762,
        title: "Joffre Lakes Provincial Park",
    },
    {
        city: "Banff",
        latitude: 51.1784,
        longitude: -115.5708,
        title: "Banff National Park",
    },
    {
        city: "Val Marie",
        latitude: 49.1233,
        longitude: -107.5423,
        title: "Grasslands National Park",
    },
    {
        city: "Churchill",
        latitude: 58.7679,
        longitude: -94.1696,
        title: "Polar Bear Capital of the World",
    },
    {
        city: "Tobermory",
        latitude: 45.2534,
        longitude: -81.6645,
        title: "Bruce Peninsula National Park",
    },
    {
        city: "Quebec City",
        latitude: 46.8131,
        longitude: -71.2075,
        title: "Quebec City Downtown",
    },
    {
        city: "Alma",
        latitude: 45.6138,
        longitude: -65.0316,
        title: "Fundy National Park",
    },
    {
        city: "Neils Harbour",
        latitude: 46.6461,
        longitude: -60.4019,
        title: "Cape Breton Highlands National Park",
    },
    {
        city: "Stanhope",
        latitude: 46.4265,
        longitude: -63.1739,
        title: "Prince Edward Island National Park",
    },
    {
        city: "Rocky Harbour",
        latitude: 49.6520,
        longitude: -57.7558,
        title: "Gros Morne National Park",
    },
    {
        city: "Seward",
        latitude: 59.8487,
        longitude: -150.1879,
        title: "Kenai Fjords National Park",
    },
    {
        city: "Grand Canyon Village",
        latitude: 36.0544,
        longitude: -112.1401,
        title: "Grand Canyon",
    },
    {
        city: "Hot Springs",
        latitude: 34.5269,
        longitude: -93.0689,
        title: "Hot Springs National Park",
    },
    {
        city: "San Francisco",
        latitude: 37.8199,
        longitude: -122.4783,
        title: "The Golden Gate Bridge",
    },
    {
        city: "Estes Park",
        latitude: 40.3428,
        longitude: -105.6836,
        title: "Rocky Mountain National Park",
    },
    {
        city: "New Haven",
        latitude: 41.3160,
        longitude: -72.9212,
        title: "Yale Peabody Museum of Natural History",
    },
    {
        city: "Bay Lake",
        latitude: 28.3772,
        longitude: -81.5707,
        title: "Disney World",
    },
    {
        city: "Atlanta",
        latitude: 33.7634,
        longitude: -84.3951,
        title: "Georgia Aquarium",
    },
    {
        city: "Halawa",
        latitude: 21.3676,
        longitude: -113.5002,
        title: "Pearl Harbor and USS Arizona Memorial",
    },
    {
        city: "Carey",
        latitude: 43.2058,
        longitude: -105.6836,
        title: "Craters of the Moon National Monument and Preserve",
    },
    {
        city: "Chicago",
        latitude: 41.8826,
        longitude: -87.6226,
        title: "Millennium Park",
    },
    {
        city: "Speedway",
        latitude: 39.7954,
        longitude: -86.2353,
        title: "Indianapolis Motor Speedway",
    },
    {
        city: "Boiling Springs",
        latitude: 40.1671,
        longitude: -77.0801,
        title: "Monroe Elementary School",
    },
    {
        city: "Bar Harbor",
        latitude: 44.3386,
        longitude: -68.2733,
        title: "Acadia National Park",
    },
    {
        city: "Boston",
        latitude: 42.3602,
        longitude: -71.0551,
        title: "Faneuil Hall Marketplace",
    },
    {
        city: "Dearborn",
        latitude: 42.3035,
        longitude: -83.2342,
        title: "Henry Ford Museum",
    },
    {
        city: "Bloomington",
        latitude: 44.8549,
        longitude: -93.2422,
        title: "Mall of America",
    },
    {
        city: "Vicksburg",
        latitude: 32.3549,
        longitude: -90.8453,
        title: "Vicksburg National Military Park",
    },
    {
        city: "St. Louis",
        latitude: 38.6251,
        longitude: -90.1868,
        title: "Gateway Arch",
    },
    {
        city: "Las Vegas",
        latitude: 36.1147,
        longitude: -115.1728,
        title: "Las Vegas Strip",
    },
    {
        city: "Carroll",
        latitude: 44.2706,
        longitude: -71.3033,
        title: "Mount Washington",
    },
    {
        city: "Atlantic City",
        latitude: 39.3539,
        longitude: -74.4382,
        title: "Atlantic City Boardwalk",
    },
    {
        city: "New York City",
        latitude: 40.7484,
        longitude: -73.9857,
        title: "Empire State Building",
    },
    {
        city: "Asheville",
        latitude: 35.5406,
        longitude: -82.5523,
        title: "Biltmore Estate",
    },
    {
        city: "Cleveland",
        latitude: 41.5085,
        longitude: -81.6954,
        title: "Rock and Roll Hall of Fame",
    },
    {
        city: "Oklahoma City",
        latitude: 35.5357,
        longitude: -97.4831,
        title: "National Cowboy and Western Heritage Museum",
    },
    {
        city: "Bridal Veil",
        latitude: 45.5762,
        longitude: -122.1158,
        title: "Multnomah Falls",
    },
    {
        city: "Philadelphia",
        latitude: 39.9495,
        longitude: -75.1497,
        title: "Independence National Historic Park",
    },
    {
        city: "Newport",
        latitude: 41.4750,
        longitude: -71.3073,
        title: "Newport mansions",
    },
    {
        city: "Memphis",
        latitude: 35.0477,
        longitude: -90.0260,
        title: "Graceland",
    },
    {
        city: "Springdale",
        latitude: 37.2982,
        longitude: -113.0263,
        title: "Zion National Park",
    },
    {
        city: "Williamsburg",
        latitude: 37.2707,
        longitude: -76.7075,
        title: "Colonial Williamsburg",
    },
    {
        city: "Seattle",
        latitude: 47.6097,
        longitude: -122.3422,
        title: "Pike Place Market",
    },
    {
        city: "Moran",
        latitude: 43.7904,
        longitude: -110.6818,
        title: "Grand Teton National Park",
    },
];