module.exports = [
    {
        city: "Duffey Lake Rd, Mount Currie, BC",
        latitude: 50.3413,
        longitude: -122.4762,
        title: "Joffre Lakes Provincial Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663697189/TopAttractions/ethan-mabunay-FDsUnae9AJc-unsplash_iibbbz.jpg",
        filename: "TopAttractions/ethan-mabunay-FDsUnae9AJc-unsplash_iibbbz",
        description: "Joffre Lakes Provincial Park is a class A provincial park located 35 kilometres east of Pemberton in British Columbia, Canada. It was established in 1996, when Joffre Lakes Recreation Area was upgraded to park status. Three glacier-fed lakes are located in the park: Lower, Middle, and Upper Joffre Lakes.",

    },
    {
        city: "Banff",
        latitude: 51.1784,
        longitude: -115.5708,
        title: "Banff National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663699330/TopAttractions/jacky-huang-6rC8fmNW3pk-unsplash_ghve0o.jpg",
        filename: "TopAttractions/jacky-huang-6rC8fmNW3pk-unsplash_ghve0o",
        description: "Banff National Park is Canadas oldest national park, established in 1885 as Rocky Mountains Park. Located in Albertas Rocky Mountains, 110 to 180 kilometres (68 to 112 mi) west of Calgary, Banff encompasses 6,641 square kilometres (2,564 sq mi) of mountainous terrain, with many glaciers and ice fields, dense coniferous forest, and alpine landscapes. The Icefields Parkway extends from Lake Louise, connecting to Jasper National Park in the north.",
    },
    {
        city: "Val Marie",
        latitude: 49.1233,
        longitude: -107.5423,
        title: "Grasslands National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663699460/TopAttractions/andrew-darlington-JKwZwIWcIio-unsplash_n53q2c.jpg",
        filename: "TopAttractions/andrew-darlington-JKwZwIWcIio-unsplash_n53q2c",
        description: "Grasslands National Park is a Canadian national park located near the village of Val Marie, Saskatchewan, and one of 44 national parks and park reserves in Canadas national park system. This national park is north of the U.S. state of Montana and lies adjacent to the international boundary.",
    },
    {
        city: "Churchill",
        latitude: 58.7679,
        longitude: -94.1696,
        title: "Polar Bear Capital of the World",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663699576/TopAttractions/hans-jurgen-mager-AZ31hv9kdzE-unsplash_kubxuj.jpg",
        filename: "TopAttractions/hans-jurgen-mager-AZ31hv9kdzE-unsplash_kubxuj.jpg",
        description: "Churchill is a town on Hudson Bay in the far north of Manitoba, Canada. Its best known for polar bears that inhabit the area in the fall, and safaris in raised, reinforced tundra vehicles allow for encounters in the wild. In summer, beluga whales are on view in the Churchill River. The area also offers the chance for wintertime Northern Lights visibility and seasonal bird-watching.",
    },
    {
        city: "Seward",
        latitude: 59.8487,
        longitude: -150.1879,
        title: "Kenai Fjords National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705203/TopAttractions/daniel-tong-vNMA0U8yxio-unsplash_n77doa.jpg",
        filename: "TopAttractions/daniel-tong-vNMA0U8yxio-unsplash_n77doa",
        description: "Kenai Fjords National Park is an American national park that maintains the Harding Icefield, its outflowing glaciers, and coastal fjords and islands. The park covers an area of 669,984 acres on the Kenai Peninsula in south-central Alaska, west of the town of Seward.",
    },
    {
        city: "Grand Canyon Village",
        latitude: 36.0544,
        longitude: -112.1401,
        title: "Grand Canyon",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705285/TopAttractions/omer-nezih-gerek-ZZnH4GOzDgc-unsplash_vzhlnf.jpg",
        filename: "TopAttractions/omer-nezih-gerek-ZZnH4GOzDgc-unsplash_vzhlnf",
        description: "The Grand Canyon in Arizona is a natural formation distinguished by layered bands of red rock, revealing millions of years of geological history in cross-section. Vast in scale, the canyon averages 10 miles across and a mile deep along its 277-mile length. Much of the area is a national park, with Colorado River white-water rapids and sweeping vistas.",
    },
    {
        city: "San Francisco",
        latitude: 37.8199,
        longitude: -122.4783,
        title: "The Golden Gate Bridge",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705455/TopAttractions/oliver-plattner-NbzjTLL95DM-unsplash_jg7ft8.jpg",
        filename: "TopAttractions/oliver-plattner-NbzjTLL95DM-unsplash_jg7ft8",
        description: "The Golden Gate Bridge is a suspension bridge spanning the Golden Gate, the one-mile-wide (1.6 km) strait connecting San Francisco Bay and the Pacific Ocean. The structure links the U.S. city of San Francisco, California—the northern tip of the San Francisco Peninsula—to Marin County, carrying both U.S. Route 101 and California State Route 1 across the strait. It also carries pedestrian and bicycle traffic, and is designated as part of U.S. Bicycle Route 95.",
    },
    {
        city: "Estes Park",
        latitude: 40.3428,
        longitude: -105.6836,
        title: "Rocky Mountain National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705537/TopAttractions/sonja-wilkinson-dIO4ZvpulPc-unsplash_bukahr.jpg",
        filename: "TopAttractions/sonja-wilkinson-dIO4ZvpulPc-unsplash_bukahr",
        description: "Rocky Mountain National Park in northern Colorado spans the Continental Divide and encompasses protected mountains, forests and alpine tundra. Its known for the Trail Ridge Road and the Old Fall River Road, drives that pass aspen trees and rivers. The Keyhole Route, a climb crossing vertical rock faces, leads up Longs Peak, the parks tallest mountain. A trail surrounding Bear Lake offers views of the peaks.",
    },
    {
        city: "Halawa",
        latitude: 21.3676,
        longitude: -157.9389,
        title: "Pearl Harbor and USS Arizona Memorial",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705949/TopAttractions/robert-linder-qZ6sCyV7Sfs-unsplash_l8gsj5.jpg",
        filename: "TopAttractions/robert-linder-qZ6sCyV7Sfs-unsplash_l8gsj5",
        description: "The USS Arizona Memorial, at Pearl Harbor in Honolulu, Hawaii, marks the resting place of 1,102 of the 1,177 sailors and Marines killed on USS Arizona during the Attack on Pearl Harbor on December 7, 1941, and commemorates the events of that day.",
    },
    {
        city: "Tobermory",
        latitude: 45.2534,
        longitude: -81.6645,
        title: "Bruce Peninsula National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663704070/TopAttractions/jennifer-chen-foi3cq_C3Co-unsplash_sveqyt.jpg",
        filename: "TopAttractions/jennifer-chen-foi3cq_C3Co-unsplash_sveqyt",
        description: "Bruce Peninsula National Park straddles the Niagara Escarpment, a huge forested ridge that runs through southern Ontario, Canada. The Grotto is a limestone cave overlooking Georgian Bays clear waters. Cliffs frame the beach at nearby Indian Head Cove. Singing Sands Beach, on Lake Huron, has shallow waters with sand dunes and a boardwalk. The Bruce Trail passes caves, forests and cliff overlooks.",
    },
    {
        city: "Quebec City",
        latitude: 46.8131,
        longitude: -71.2075,
        title: "Quebec City Downtown",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663704220/TopAttractions/rich-martello-tgbd0IjWoeQ-unsplash_mcwsry.jpg",
        filename: "TopAttractions/rich-martello-tgbd0IjWoeQ-unsplash_mcwsry",
        description: "Quebec City sits on the Saint Lawrence River in Canadas mostly French-speaking Québec province. Dating to 1608, it has a fortified colonial core, Vieux-Québec and Place Royale, with stone buildings and narrow streets. This area is the site of the towering Chateau Frontenac Hotel and imposing Citadelle of Quebec. The Petit Champlain districts cobblestone streets are lined with bistros and boutiques.",
    },
    {
        city: "Alma",
        latitude: 45.6138,
        longitude: -65.0316,
        title: "Fundy National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663704385/TopAttractions/daniel-hansen-QV_JAkhOViQ-unsplash_xcfzja.jpg",
        filename: "TopAttractions/daniel-hansen-QV_JAkhOViQ-unsplash_xcfzja",
        description: "Fundy National Park is a national park of Canada located on the Bay of Fundy, near the village of Alma, New Brunswick. It was officially opened on 29 July 1950. The Park showcases a rugged coastline which rises up to the Canadian Highlands, the highest tides in the world and more than 25 waterfalls.",
    },
    {
        city: "Neils Harbour",
        latitude: 46.6461,
        longitude: -60.4019,
        title: "Cape Breton Highlands National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663704575/TopAttractions/elyse-turton-9M478YLamG0-unsplash_og9uf1.jpg",
        filename: "TopAttractions/elyse-turton-9M478YLamG0-unsplash_og9uf1",
        description: "Cape Breton Island is at the eastern end of the Canadian province of Nova Scotia. Its Cabot Trail is a roadway encircling the island, passing forests and rugged coastline. The drive skirts Cape Breton Highlands National Park, whose Skyline Trail footpath overlooks the Gulf of St. Lawrence, known for migratory whales. The town of Sydney honours local music with the Big Fiddle, a giant violin statue on the waterfront.",
    },
    {
        city: "Stanhope",
        latitude: 46.4265,
        longitude: -63.1739,
        title: "Prince Edward Island National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663704675/TopAttractions/tobias-negele-GhBXWlqpGDs-unsplash_lep3hf.jpg",
        filename: "TopAttractions/tobias-negele-GhBXWlqpGDs-unsplash_lep3hf",
        description: "Prince Edward Island is one of eastern Canadas maritime provinces, off New Brunswick and Nova Scotia in the Gulf of St. Lawrence. The large island is marked by red-sand beaches, lighthouses, and fertile farmland, and is renowned for seafood like lobster and mussels. Charlottetown, the capital, is home to Victorian government buildings and the modern Confederation Centre of the Arts, with a theatre and art gallery.",
    },
    {
        city: "Rocky Harbour",
        latitude: 49.6520,
        longitude: -57.7558,
        title: "Gros Morne National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663704792/TopAttractions/marcus-urbenz-xeP9SDCCQWA-unsplash_y1ccso.jpg",
        filename: "TopAttractions/marcus-urbenz-xeP9SDCCQWA-unsplash_y1ccso",
        description: "Gros Morne National Park lies on the west coast of the island of Newfoundland, in eastern Canada. Gros Morne, a peak in the Long Range Mountains, has a trail overlooking the Ten Mile Pond gorge. Western Brook Pond, a fjord formed by glaciers, is lined with cliffs and waterfalls, including Pissing Mare Falls. The desert-like Tablelands area has unusual rock formations created by the earths tectonic plates colliding.",
    },
    {
        city: "Hot Springs",
        latitude: 34.5269,
        longitude: -93.0689,
        title: "Hot Springs National Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705368/TopAttractions/levan-badzgaradze-ptypzLJqZjg-unsplash_ot87qx.jpg",
        filename: "TopAttractions/levan-badzgaradze-ptypzLJqZjg-unsplash_ot87qx",
        description: "Hot Springs National Park is an American national park in central Garland County, Arkansas, adjacent to the city of Hot Springs, the county seat. Hot Springs Reservation was initially created by an act of the United States Congress on April 20, 1832, to be preserved for future recreation.",
    },
    {
        city: "Bay Lake",
        latitude: 28.3772,
        longitude: -81.5707,
        title: "Disney World",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705676/TopAttractions/brian-mcgowan-hCzdRs3tZMw-unsplash_pzxieh.jpg",
        filename: "TopAttractions/brian-mcgowan-hCzdRs3tZMw-unsplash_pzxieh",
        description: "The Walt Disney World Resort, also called Walt Disney World or simply Disney World, is an entertainment resort complex in Bay Lake and Lake Buena Vista, Florida, United States, near the cities of Orlando and Kissimmee. Opened on October 1, 1971, the resort is operated by Disney Parks, Experiences and Products, a division of The Walt Disney Company.",
    },
    {
        city: "Atlanta",
        latitude: 33.7634,
        longitude: -84.3951,
        title: "Georgia Aquarium",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663705864/TopAttractions/erik-o990dFLgo1Q-unsplash_isf9pl.jpg",
        filename: "TopAttractions/erik-o990dFLgo1Q-unsplash_isf9pl",
        description: "Georgia Aquarium is a public aquarium in Atlanta, Georgia, United States. It exhibits hundreds of species and thousands of animals across its seven major galleries, all of which reside in more than 11 million US gallons of water. The Georgia Aquarium remains the largest aquarium in the United States and the third largest in the world.",
    },
    {
        city: "Chicago",
        latitude: 41.8826,
        longitude: -87.6226,
        title: "Millennium Park",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663706033/TopAttractions/wicker-woodsong-kouAo3VSP6g-unsplash_kiw5qz.jpg",
        filename: "TopAttractions/wicker-woodsong-kouAo3VSP6g-unsplash_kiw5qz",
        description: "Millennium Park is a public park located in the Loop community area of Chicago, operated by the Chicago Department of Cultural Affairs. The park, opened in 2004 and intended to celebrate the third millennium, is a prominent civic center near the citys Lake Michigan shoreline that covers a 24.5-acre (9.9 ha) section of northwestern Grant Park.",
    },
    {
        city: "New York City",
        latitude: 40.7484,
        longitude: -73.9857,
        title: "Empire State Building",
        url: "https://res.cloudinary.com/dxn4egwyq/image/upload/v1663706153/TopAttractions/todd-quackenbush-GMTx7uC6lNc-unsplash_vh2nlo.jpg",
        filename: "TopAttractions/todd-quackenbush-GMTx7uC6lNc-unsplash_vh2nlo",
        description: "The Empire State Building is a 102-story Art Deco skyscraper in Midtown Manhattan, New York City. The building was designed by Shreve, Lamb and Harmon and built from 1930 to 1931. Its name is derived from Empire State, the nickname of the state of New York.",
    },
];